// <auto-generated />
namespace A2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class AddPosterPath : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddPosterPath));
        
        string IMigrationMetadata.Id
        {
            get { return "202409201734290_AddPosterPath"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
